import React, { Component } from 'react';
import { StyleSheet, Text, View, ImageBackground, NetInfo, Button } from 'react-native';

const axios = require('axios')
const PushNotification = require('react-native-push-notification');

PushNotification.configure({

  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function (token) {
    console.log('TOKEN:', token);
  },

  // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {
    console.log('NOTIFICATION:', notification);

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for local notifications, but is need to receive remote push notifications)
  senderID: "YOUR GCM (OR FCM) SENDER ID",

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },

  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: false,

  /**
    * (optional) default: true
    * - Specified if permissions (ios) and token (android and ios) will requested or not,
    * - if not, you must call PushNotificationsHandler.requestPermissions() later
    */
  requestPermissions: true,
});
export default class App extends Component {
  state = {
    result: '',
    currentWarning: 'same'
  }

  componentDidMount() {
    this.state.result.warning
  }

  handleNotification = (message) => {

    PushNotification.localNotification({
      /* Android Only Properties */
      id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: "My Notification Ticker", // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
      smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: message, // (optional) default: "message" prop
      subText: "Landslide Warning", // (optional) default: none
      color: "red", // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: "group", // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      priority: "high", // (optional) set notification priority, default: high
      visibility: "private", // (optional) set notification visibility, default: private
      importance: "high", // (optional) set notification importance, default: high

      /* iOS and Android properties */
      title: "My Notification Title", // (optional)
      message: message, // (required)
      playSound: false, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 1, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      // repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
      // actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });

  }
  getData = async (localWarning) => {
    try {
      response = NetInfo.isConnected ? await axios.get("http://192.168.56.1/webpage/getWarning.php") : alert('No internet')
      await console.log('payload', response.data)
      await this.setResult(response.data, localWarning)
    } catch {
      console.log('error')
    }
  }
  setResult = (response, localWarning) => {
    payload = response[0]
    this.setState({
      result: payload
    })
    if (payload.warning === localWarning) {
      this.handleMessage(payload.warning, false)
    } else {
      this.handleMessage(payload.warning, true)
    }

  }

  handleMessage = (payloadWarning, shouldNotify) => {
    console.log('handleMessage', shouldNotify)
    if (shouldNotify) {
      if (payloadWarning === 'Red') {
        this.handleNotification('Red')
      } else if (payloadWarning === 'Yellow') {
        this.handleNotification('Yellow')
      } else if (payloadWarning === 'Orange') {
        this.handleNotification('Orange')
      } else {

      }
    } else {
      console.log('No new warning')
    }

  }
  render() {
    const red = '#9C090E'
    const orange = '#FF760B'
    const yellow = '#F0C415'
    const disabled = '#3C3C3C'
    let warningColor = this.state.result.warning
    return (
      <View style={styles.container}>
        <ImageBackground source={require('./mountain.jpg')} style={{ height: '100%', width: '100%', justifyContent: 'center', alignItems: 'center' }}>

          <View style={styles.container}>
            <Text style={styles.title}>LANDSLIDE <Text style={{ fontWeight: 'normal', fontSize: 36 }}>ADVISORY</Text></Text>
          </View>
          <View style={[styles.warning, { backgroundColor: warningColor === 'Red' ? red : disabled }]}>
            <View style={{ flex: 1.1 }}>
              <Text style={{ fontWeight: 'bold', fontSize: 30, color: '#fff' }}>RED </Text>
              <Text style={{ fontWeight: 'normal', fontSize: 30, color: '#fff' }}>WARNING</Text>
            </View>
            <View style={styles.warningMessageContainer}>
              <Text style={styles.warningMessage}>
                Highly Susceptible! Be Alert and Ready to Evacuate.</Text></View>
          </View>

          <View style={[styles.warning, { backgroundColor: warningColor === 'Orange' ? orange : disabled }]}>
            <View style={{ flex: 1.1 }}>
              <Text style={{ fontWeight: 'bold', fontSize: 30, color: '#fff' }}>ORANGE </Text>
              <Text style={{ fontWeight: 'normal', fontSize: 30, color: '#fff' }}>WARNING</Text>
            </View>
            <View style={styles.warningMessageContainer}>
              <Text style={styles.warningMessage}>
                Susceptible! Be Cautious.</Text></View>
          </View>

          <View style={[styles.warning, { backgroundColor: warningColor === 'Yellow' ? yellow : disabled }]}>
            <View style={{ flex: 1.1 }}>
              <Text style={{ fontWeight: 'bold', fontSize: 30, color: '#fff' }}>YELLOW </Text>
              <Text style={{ fontWeight: 'normal', fontSize: 30, color: '#fff' }}>WARNING</Text>
            </View>
            <View style={styles.warningMessageContainer}>
              <Text style={styles.warningMessage}>
                Marginally Stable! Be Prepared.</Text></View>
          </View>

          <View style={styles.container}>
            <Text style={styles.details}>San Martin, Angono, Rizal</Text>
            <Text style={{ fontSize: 18, color: '#fff' }}>{this.state.result.timestamp}</Text>
          </View>
          <View onPress={this.getData(this.state.result.warning)} />
        </ImageBackground>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 36,
    textAlign: 'center',
    margin: 10,
    fontWeight: 'bold',
    color: '#000',
  },
  details: {
    fontSize: 18,
    color: '#fff'
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  warning: {
    flex: 1,
    maxHeight: 120,
    width: '80%',
    backgroundColor: '#fff',
    margin: 10,
    padding: 15,
    flexDirection: 'row',
    // borderRadius: 75
  },
  warningMessage: {
    fontWeight: 'normal',
    fontSize: 16,
    color: '#fff'
  },
  warningMessageContainer: {
    flex: 0.9,
    justifyContent: 'center'
  },
});


